name: isolate_bloc_test_example

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  isolate_bloc: 
    path: ../../isolate_bloc/
  isolate_bloc_test:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: