name: isolate_bloc
description: A dart package that helps implement the BLoC pattern. BLoC works in Isolate and don't slow down UI.
version: 2.0.1
homepage: https://github.com/Maksimka101/isolate-bloc/tree/master/packages/isolate_bloc
repository: https://github.com/Maksimka101/isolate-bloc/tree/master/packages/isolate_bloc

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  provider: ^6.0.0
  uuid: ^3.0.4

dev_dependencies:
  all_lint_rules_community: ^0.0.9
  dart_code_metrics: ^4.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  path: ^1.8.0
  