name: isolate_bloc action

on:
  push:
    paths:
      - "packages/isolate_bloc/**"
    paths-ignore:
      - "**/*README*.md"
  workflow_dispatch:

jobs:
  analyze:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: |
          cd  packages/isolate_bloc
          flutter pub get
          flutter analyze

  test:
    name: flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "8"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: |
          cd  packages/isolate_bloc
          flutter pub get
          flutter test --coverage
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./packages/isolate_bloc/coverage
